### PR TITLE
Swift 2.0

### PR DESCRIPTION
**Pull request by kostiakoval**
Swift 2.0 Plus Async code cleanup

### CODE REVIEW

**Comment by kostiakoval** [comment]
Hi @nixzhu I do a lot of improvements to Swift 2.0 version, How Would you like to get those RP, as a separate one? you could make a new branch

**Comment by nixzhu** [comment]
The change of switch case in LocationDelegate from your PR  may have a bug, because the delegate method may been called when user considering, we don't need handle all cases (In face, user have not chance to change CLAuthorizationStatus to .NotDetermined or .Restricted when App running)

After Xcode 7 GM released, I will make this repo Swift 2 ready.

**Comment by kostiakoval** [comment]
hmm.  Interesting. But it's very strange that for the users of that library that no callback is called if the fail happens.
Now see what you meant. I will revert that change.

**Comment by kostiakoval** [comment]
I'm working on Swift 2.0 now so why don't start adding support now? if you could make a new brach swift_2.0 I could make a new separate RP with. Right now it contains 3 PR here, which makes it's harder to merge
@nixzhu

**Comment by kostiakoval** [comment]
I'm sorry for this chaos :( I've splitter all the changes into separate RP and removed wrong location permissions

**Pull request closed without merging**
