### PR TITLE
Added SPM support for Swift 5

### PR DESCRIPTION
**Pull request by mohpor**
Signed-off-by: Mohammad Porooshani <porooshani@gmail.com>

### CODE REVIEW

**Comment by nixzhu** [comment]
Thanks

**Comment by mohpor** [comment]
@nixzhu Thanks for merging this PR.
Could you please push another tag (e.g. `1.2.3`) to the repo, otherwise we need to point to `master` branch instead of latest version.

**Comment by nixzhu** [comment]
@mohpor Done.

**Comment by mohpor** [comment]
Perfect.
Thanks

**Pull request merged**
